# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matsp <- function(G) {
    .Call(`_SCANG_matsp`, G)
}

Liumod <- function(Cov, q) {
    .Call(`_SCANG_Liumod`, Cov, q)
}

SCANG_O_Search <- function(G, X, working, sigma, fam, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f) {
    .Call(`_SCANG_SCANG_O_Search`, G, X, working, sigma, fam, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f)
}

SCANG_O_Search_Relatedness <- function(G, P, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f) {
    .Call(`_SCANG_SCANG_O_Search_Relatedness`, G, P, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f)
}

SCANG_O_Search_Relatedness_sp <- function(G, Sigma_i, Sigma_iX, cov, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f) {
    .Call(`_SCANG_SCANG_O_Search_Relatedness_sp`, G, Sigma_i, Sigma_iX, cov, residuals, threshold_o, threshold_s, threshold_b, Lmax, Lmin, steplength, weights_B, weights_S, begid, filter, f)
}

SCANG_O_Thres <- function(G, X, working, sigma, fam, times, Lmax, Lmin, steplength, weights_B, weights_S, filter) {
    .Call(`_SCANG_SCANG_O_Thres`, G, X, working, sigma, fam, times, Lmax, Lmin, steplength, weights_B, weights_S, filter)
}

SCANG_O_Thres_Relatedness <- function(G, P, pesudo_residuals, times, Lmax, Lmin, steplength, weights_B, weights_S, filter) {
    .Call(`_SCANG_SCANG_O_Thres_Relatedness`, G, P, pesudo_residuals, times, Lmax, Lmin, steplength, weights_B, weights_S, filter)
}

SCANG_O_Thres_Relatedness_sp <- function(G, Sigma_i, Sigma_iX, cov, pesudo_residuals, times, Lmax, Lmin, steplength, weights_B, weights_S, filter) {
    .Call(`_SCANG_SCANG_O_Thres_Relatedness_sp`, G, Sigma_i, Sigma_iX, cov, pesudo_residuals, times, Lmax, Lmin, steplength, weights_B, weights_S, filter)
}

maxO <- function(p, Lmax, Lmin, steplength, x, weights_B, weights_S, Cov, filter, times) {
    .Call(`_SCANG_maxO`, p, Lmax, Lmin, steplength, x, weights_B, weights_S, Cov, filter, times)
}

regionfilter <- function(candidate, f) {
    .Call(`_SCANG_regionfilter`, candidate, f)
}

svd_c <- function(X) {
    .Call(`_SCANG_svd_c`, X)
}

